spring:
  application:
    name: urlShortner

  datasource:
    url: jdbc:mysql://localhost:3306/urlusers?createDatabaseIfNotExist=true
    username: root
    password: #yourpassword

#Jpa Configuration
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

# Logging level (optional but handy)
  jwt:
    secret: secret
